### ISSUE TITLE
Script broken, need to update login_strava() function

### ISSUE THREAD

**Issue by normcyr** [simark/kudos-normand#6]
``Traceback (most recent call last):
  File "kudos.py", line 79, in <module>
    browser, csrf_token, feed_page = login_strava(email, password)
  File "kudos.py", line 26, in login_strava
    login_form = login_page.soup.select("#login_form")[0]
IndexError: list index out of range``

Strava has updated their login page. We need to adjust the script accordingly.

**Comment by simark** [comment]
I think it's transient issues, like when there is a downtime.  We should definitely improve the script to better handle cases like this.
